### ISSUE TITLE
RNG Coronach set doesn't like starting with 2x katana:

### ISSUE THREAD

**Issue by IzaKastra** [IzaKastra/wsdist#6]
---------------
Checking:  Coronach  TP=[1500,1800]
---------------
Current iteration: 1
Traceback (most recent call last):
  File "gui_wsdist.py", line 784, in <module>
    best_set = run_weaponskill(main_job, sub_job, ws_name, min_tp, max_tp, n_iter, n_sims, check_gear, check_slots, buffs, enemy, starting_gearset, show_final_plot, False, spell, job_abilities, burst)
  File "/Users/kastra/del/wsdist/wsdist.py", line 938, in run_weaponskill
    if ws_name not in ws_dict[new_set["main"]["Skill Type"]] and ws_name not in ws_dict["Archery"]+ws_dict["Marksmanship"]:
KeyError: 'None'

**Comment by IzaKastra** [comment]
Add a checkbox for True Shot.

**Comment by IzaKastra** [comment]
Trueflight is using incorrect WSC

**Comment by IzaKastra** [comment]
COR Empy+3 hands missing Crit Rate+8
